import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import { createClient } from '@/lib/supabase/server'
import { GenreSelectionModal } from '@/components/onboarding/GenreSelectionModal'
import { LiveChat } from '@/components/LiveChat'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  let showOnboarding = false
  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('favorite_genres')
      .eq('id', user.id)
      .single()

    if (profile && (!profile.favorite_genres || profile.favorite_genres.length === 0)) {
      showOnboarding = true
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        {children}
        {showOnboarding && user && <GenreSelectionModal isOpen={true} userId={user.id} />}
        <LiveChat user={user} />
      </body>
    </html>
  );
}
