create table user_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  movie_id integer not null,
  action text not null check (action in ('like', 'watchlist')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, movie_id, action)
);

-- RLS Policies
alter table user_interactions enable row level security;

create policy "Users can view their own interactions"
  on user_interactions for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own interactions"
  on user_interactions for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own interactions"
  on user_interactions for delete
  using ( auth.uid() = user_id );
